# Generated by Django 6.0.6 on 2026-06-10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckStop",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "opis_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "median_price",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "geohash",
                    models.CharField(blank=True, db_index=True, max_length=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name"], name="stations_tr_name_d80ac5_idx"
                    ),
                    models.Index(
                        fields=["geohash"], name="stations_tr_geohash_994d0a_idx"
                    ),
                ],
            },
        ),
    ]
